### ISSUE TITLE
Use of this library for Arduino IDE results in errors with reference types for unpacking

### ISSUE THREAD

**Issue by JesseCake** [gbr1/ucPack#1]
It appears there are problems with the way the unpack functions are written with pointers/references.

Use of the unpacket functions results in compile errors like this:
`
cannot bind non-const lvalue reference of type 'uint8_t& {aka unsigned char&}' to an rvalue of type 'uint8_t {aka unsigned char}'`

**Comment by gbr1** [comment]
hi @JesseCake! 
Thank you for using my library!
can you give more information about your usage. 
I'm using it with ROS2 (C++1z) and various Arduino boards without any issues.

Some code is appreciated!

**Comment by JesseCake** [comment]
Hi there! Thanks for getting back to me so quickly.

Actually I've just solved it - I was using the example code from your ROS2 node for Arduino and it seems that's where the error came from :

Your code was passing a char into the function ("c") which it didn't like. I switched to a uint8_t and it was happier.

I also noticed you're using a variable "dim" which isn't defined further up which means the example code doesn't work. Might be worth dropping a new example in there.

Thanks for your hard work - your code is about to start driving a 2.5 tonne hydraulic robot outdoors!

Perhaps as I continue work, I might contribute back some code to expand data types possible over the interface?

**Comment by gbr1** [comment]
Of course! Keep me updated about your progresses!

if you need a complex reference code check here: [https://github.com/gbr1/stm32_amr_firmware](https://github.com/gbr1/stm32_amr_firmware)

I often publish news on developments on [twitter](https://twitter.com/br1johnny) and [instagram](https://instagram.com/johnnyrobomeka)

I close this issue!
